server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

hubspot:
  client-id: ${HUBSPOT_CLIENT_ID}
  client-secret: ${HUBSPOT_CLIENT_SECRET}
  redirect-uri: ${HUBSPOT_REDIRECT_URI}
  scopes: ${HUBSPOT_SCOPES}
  auth-url: ${HUBSPOT_AUTH_URL}
  token-url: ${HUBSPOT_TOKEN_URL}
  api-url: ${HUBSPOT_API_URL}

resilience4j:
  ratelimiter:
    instances:
      hubspotRateLimiter:
        limit-for-period: 190
        limit-refresh-period: 10s
        timeout-duration: 0

circuitbreaker:
  instances:
    hubspotCircuitBreaker:
      register-health-indicator: true
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      minimum-number-of-calls: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true
